### ISSUE TITLE
Installation fails on precompile due to SimpleNonlinearSolve.jl

### ISSUE THREAD

**Issue by Alexsp32** [NQCD/NQCDynamics.jl#308] opened 2023-11-06 10:45 UTC
Adding NQCDynamics to a brand new Julia 1.9.3 environment fails on precompilation as follows, making NQCDynamics unusable:

```
Precompiling project...
  ✗ SimpleNonlinearSolve
  ✗ NonlinearSolve
  ✗ OrdinaryDiffEq
  ✗ AdvancedHMC → AdvancedHMCOrdinaryDiffEqExt
  ✗ StochasticDiffEq
  ✗ NQCDynamics
  0 dependencies successfully precompiled in 22 seconds. 271 already precompiled.

ERROR: The following 1 direct dependency failed to precompile:

NQCDynamics [36248dfb-79eb-4f4d-ab9c-e29ea5f33e14]

Failed to precompile NQCDynamics [36248dfb-79eb-4f4d-ab9c-e29ea5f33e14] to "/Users/u5529589/.julia/compiled/v1.9/NQCDynamics/jl_veBRBA".
ERROR: LoadError: UndefVarError: `NonlinearLeastSquaresProblem` not defined
Stacktrace:
 [1] top-level scope
   @ ~/.julia/packages/SimpleNonlinearSolve/nusbP/src/raphson.jl:66
 [2] include(mod::Module, _path::String)
   @ Base ./Base.jl:457
 [3] include(x::String)
   @ SimpleNonlinearSolve ~/.julia/packages/SimpleNonlinearSolve/nusbP/src/SimpleNonlinearSolve.jl:1
 [4] top-level scope
   @ ~/.julia/packages/SimpleNonlinearSolve/nusbP/src/SimpleNonlinearSolve.jl:30
 [5] include
   @ ./Base.jl:457 [inlined]
 [6] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::String)
   @ Base ./loading.jl:2049
 [7] top-level scope
   @ stdin:3
in expression starting at /Users/u5529589/.julia/packages/SimpleNonlinearSolve/nusbP/src/raphson.jl:66
in expression starting at /Users/u5529589/.julia/packages/SimpleNonlinearSolve/nusbP/src/SimpleNonlinearSolve.jl:1
in expression starting at stdin:3
ERROR: LoadError: Failed to precompile SimpleNonlinearSolve [727e6d20-b764-4bd8-a329-72de5adea6c7] to "/Users/u5529589/.julia/compiled/v1.9/SimpleNonlinearSolve/jl_yQohNd".
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base ./loading.jl:2300
  [3] compilecache
    @ ./loading.jl:2167 [inlined]
  [4] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:1805
  [5] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1660
  [6] macro expansion
    @ ./loading.jl:1648 [inlined]
  [7] macro expansion
    @ ./lock.jl:267 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1611
  [9] include
    @ ./Base.jl:457 [inlined]
 [10] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::String)
    @ Base ./loading.jl:2049
 [11] top-level scope
    @ stdin:3
in expression starting at /Users/u5529589/.julia/packages/OrdinaryDiffEq/JJd6g/src/OrdinaryDiffEq.jl:1
in expression starting at stdin:3
ERROR: LoadError: Failed to precompile OrdinaryDiffEq [1dea7af3-3e70-54e6-95c3-0bf5283fa5ed] to "/Users/u5529589/.julia/compiled/v1.9/OrdinaryDiffEq/jl_v4UvnP".
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base ./loading.jl:2300
  [3] compilecache
    @ ./loading.jl:2167 [inlined]
  [4] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:1805
  [5] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1660
  [6] macro expansion
    @ ./loading.jl:1648 [inlined]
  [7] macro expansion
    @ ./lock.jl:267 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1611
  [9] include(mod::Module, _path::String)
    @ Base ./Base.jl:457
 [10] include(x::String)
    @ NQCDynamics ~/.julia/packages/NQCDynamics/Wb3nf/src/NQCDynamics.jl:1
 [11] top-level scope
    @ ~/.julia/packages/NQCDynamics/Wb3nf/src/NQCDynamics.jl:34
 [12] include
    @ ./Base.jl:457 [inlined]
 [13] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
    @ Base ./loading.jl:2049
 [14] top-level scope
    @ stdin:3
in expression starting at /Users/u5529589/.julia/packages/NQCDynamics/Wb3nf/src/DynamicsMethods/DynamicsMethods.jl:1
in expression starting at /Users/u5529589/.julia/packages/NQCDynamics/Wb3nf/src/NQCDynamics.jl:1
in expression starting at stdin:3
```

**Comment by jamesgardner1421** [comment] 2023-11-06 10:53
I have also seen this just this morning as well. I've been trying to update some dependencies so may have been caused by me. It seems like one of these dependencies has a broken version but I think they've already fixed it. I just have to finish updating the compat entries for NQCDynamics and it should be fixed

**Closed** 2023-11-06 12:25 UTC
Labels: bug
